#!/bin/sh
pacman -S bluez bluez-utils discord dmenu docker go i3status iwd jq keepassxc kubectl libxft2 networkmanager openssh pavucontrol pulseaudio python-pip redshift rsync rxvt-unicode vscode xclip xorg-xbacklight xorg-xinit xorg-xrandr xterm yarn 
